version: '3.3'
 
services:
  web:
    image: nginx:latest # nginx 이미지
    container_name: nhsign-client # 컨테이너 명
    restart: "on-failure" # 구동 실패 시 재시작
    ports:
      - 80:80
    volumes: # 볼륨 설정
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./client/build:/usr/share/nginx/html
 
  server:
    build: # Dockerfile 빌드
      context: ./server # Dockerfile 빌드 경로
    container_name: nhsign-server # 컨테이너 명
    restart: "on-failure"
    # expose:
    #   - 5000 # 도커 내부적 포트
    ports:
      - 5000:5000
    depends_on:
      - mongo
    volumes: # 볼륨 설정
      - './server:/app'
      - '/app/node_modules'
      - type: bind 
        source: /Users/niceharu/Dev/Data/storage # local 경로
        target: /app/storage  # container 내부에서의 경로
    environment: # 환경변수 설정
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
    tty: true

  mongo:
    image: mongo:4.4.1-bionic
    container_name: mongo
    ports:
      - 27027:27017
    volumes:
    - type: bind 
      source: /Users/niceharu/Dev/Data/mongodb # local 경로
      target: /data/db  # container 내부에서의 경로