version: '3.3'
 
services:
  # admin:
  #   build: # Dockerfile 빌드
  #     context: ./admin # Dockerfile 빌드 경로
  #   image: nhsign-admin:2.2.3
  #   container_name: nhsign-admin # 컨테이너 명
  #   restart: always
  #   ports:
  #     - 4002:3002
  #   volumes: # 볼륨 설정
  #     - ./admin/build:/app/build

  broker:
    build: # Dockerfile 빌드
      context: ./broker # Dockerfile 빌드 경로
      args:
      - SERVER_MODE=REAL
      - JAR_VERSION=broker-0.0.2.jar
    container_name: nhsign_broker # 컨테이너 명
    restart: always
    ports:
      - 4001:4001
    volumes: # 볼륨 설정
      - ./broker/fsdinit/:/app/fsdinit
      - ./server/storage/:/app/storage

  web:
    build: # Dockerfile 빌드
      context: ./client # Dockerfile 빌드 경로
    image: nhsign-client:2.2.3
    container_name: nhsign-client # 컨테이너 명
    restart: "on-failure"
    ports:
      - 3000:3000
    # volumes: # 볼륨 설정
      # - ./client/build:/app/build
    # image: nginx:latest # nginx 이미지
    # container_name: nhsign-client # 컨테이너 명
    # restart: "on-failure" # 구동 실패 시 재시작
    # ports:
    #   - 80:80
    # volumes: # 볼륨 설정
    #   - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    #   - ./client/build:/usr/share/nginx/html
    environment:
      - NODE_ENV=production
 
  server:
    build: # Dockerfile 빌드
      context: ./server # Dockerfile 빌드 경로
    image: nhsign-server:2.2.3
    container_name: nhsign-server # 컨테이너 명
    restart: "on-failure"
    # expose:
    #   - 5000 # 도커 내부적 포트
    ports:
      - 5001:5000
    depends_on:
      - mongo
    volumes: # 볼륨 설정
      - ./server/storage/:/app/storage
      # - ./server:/app
      # - '/app/node_modules' 
      # - type: bind 
        # source: /Users/niceharu/Dev/Data/storage # local 경로
        # target: /app/storage  # container 내부에서의 경로
        # source: /Users/niceharu/Dev/nhsign-docker/server # local 경로
        # target: /app  # container 내부에서의 경로
    environment: # 환경변수 설정
      - NODE_ENV=production
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
    tty: true

  mongo:
    image: mongo:4.4.1-bionic
    container_name: mongo
    ports:
      - 27027:27017
    volumes:
    - type: bind 
      source: /Users/niceharu/Dev/Data/mongodb # local 경로
      target: /data/db  # container 내부에서의 경로