version: '3.8'

services:
  admin:
     build:
       context: ./admin
     image: nhsign-admin:2.2.5
     container_name: nhsign-admin
     restart: always
     ports:
       - 4002:3002
     volumes:
       - ./admin:/app                    # 실시간 반영 추가
       - /app/node_modules
       - ./admin/build:/app/build

  broker:
    build:
      context: ./broker
      args:
      - SERVER_MODE=REAL
      - JAR_VERSION=broker-0.0.2.jar
    container_name: nhsign_broker
    restart: always
    ports:
      - 4001:4001
    volumes:
      - ./broker/fsdinit/:/app/fsdinit
      - ./server/storage/:/app/storage

  web:
    build:
      context: ./client
    image: nhsign-client:2.2.7
    container_name: nhsign-client
    restart: "on-failure"
    ports:
      - 3000:3000
    volumes:                            # 실시간 반영 추가
      - ./client:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development            # production → development
      - CHOKIDAR_USEPOLLING=true

  mobile:
    build:
      context: ./mobile
    image: nhsign-mobile:2.2.7
    container_name: nhsign-mobile
    restart: "on-failure"
    ports:
      - 3004:3004
    volumes:                            # 실시간 반영 추가
      - ./mobile:/app
      - /app/node_modules

  server:
    build:
      context: ./server
    image: nhsign-server:2.2.6
    container_name: nhsign-server
    restart: "on-failure"
    ports:
      - 5001:5000
    depends_on:
      - mongo
    volumes:
      - ./server:/app                   # 주석 해제!
      - /app/node_modules               # 주석 해제!
      - ./server/storage/:/app/storage
    environment:
      - NODE_ENV=development            # production → development
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
    tty: true

  mongo:
    image: mongo:4.4.1-bionic
    container_name: mongo
    ports:
      - 27027:27017
    volumes:
      - mongodb_data:/data/db           # Docker 볼륨 사용

volumes:
  mongodb_data:                         # Docker 볼륨 정의